version: "3.8"

services:
  crisis-labs:
    image: jviou/crisis-labs:latest
    container_name: crisis-labs
    restart: unless-stopped
    ports:
      - "8069:8080"  # 8069 côté host, 8080 dans le conteneur
